(("a" . "seo")
 ("c" . "Hello Web Admin, I noticed that\n")
 ("d" . "1448913859968688486")
 ("e" . "dsqbketcxa@example.com")
 ("i" . "535")
 ("s" . "Submit Comment")
 ("u" . "http://www.example.com/")
 ("v" . "seo")
 ("x" . "seo"))
