/*
 * Copyright (c) 2018 Josef 'Jeff' Sipek <jeffpc@josefsipek.net>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#define TEST_TREE_BST

#include "test_tree_common.c"

static struct test2 checks2[2] = {
	[true]  = {
		"ascending",
		{ &a, NULL, &b },
		{
			{ &a, { &b } },
			{ &b, { &a } },
		},
	},
	[false] = {
		"descending",
		{ &b, &a, NULL },
		{
			{ &a, { &b } },
			{ &b, { &a } },
		},
	},
};

static struct test3 checks3[6] = {
	[0] = {
		.pre = { &a,
			 NULL, &b,
			 NULL, NULL, NULL, &c },
		.sub = {
			[0] = { &a, { &b, NULL, &c }, },
			[1] = { &b, { &a, NULL, &c }, },
			[2] = { &c, { &a, NULL, &b }, },
		},
	},
	[1] = {
		.pre = { &a,
			 NULL, &c,
			 NULL, NULL, &b, NULL },
		.sub = {
			[0] = { &a, { &c, &b, NULL }, },
			[1] = { &b, { &a, NULL, &c }, },
			[2] = { &c, { &a, NULL, &b }, },
		},
	},
	[2] = {
		.pre = { &b,
			 &a, &c },
		.sub = {
			[0] = { &a, { &b, NULL, &c }, },
			[1] = { &b, { &c, &a, NULL }, },
			[2] = { &c, { &b, &a, NULL }, },
		},
	},
	[3] = {
		.pre = { &b,
			 &a, &c },
		.sub = {
			[0] = { &a, { &b, NULL, &c }, },
			[1] = { &b, { &c, &a, NULL }, },
			[2] = { &c, { &b, &a, NULL }, },
		},
	},
	[4] = {
		.pre = { &c,
			 &a, NULL,
			 NULL, &b, NULL, NULL },
		.sub = {
			[0] = { &a, { &c, &b, NULL }, },
			[1] = { &b, { &c, &a, NULL }, },
			[2] = { &c, { &a, NULL, &b }, },
		},
	},
	[5] = {
		.pre = { &c,
			 &b, NULL,
			 &a, NULL, NULL, NULL },
		.sub = {
			[0] = { &a, { &c, &b, NULL }, },
			[1] = { &b, { &c, &a, NULL }, },
			[2] = { &c, { &b, &a, NULL }, },
		},
	},
};

static struct test4 checks4[24] = {
	[0]  = {
		.pre = { &a,
			 NULL, &b,
			 NULL, NULL, NULL, &c,
			 NULL, NULL, NULL, NULL, NULL, NULL, NULL, &d },
		.sub = {
			[0] = { &a,
				{ &b,
				  NULL, &c,
				  NULL, NULL, NULL, &d },
			},
			[1] = { &b,
				{ &a,
				  NULL, &c,
				  NULL, NULL, NULL, &d },
			},
			[2] = { &c,
				{ &a,
				  NULL, &b,
				  NULL, NULL, NULL, &d },
			},
			[3] = { &d,
				{ &a,
				  NULL, &b,
				  NULL, NULL, NULL, &c },
			},
		},
	},
	[1]  = {
		.pre = { &a,
			 NULL, &c,
			 NULL, NULL, &b, &d },
		.sub = {
			[0] = { &a, TEST3_CBD },
			[1] = { &b,
				{ &a,
				  NULL, &c,
				  NULL, NULL, NULL, &d },
			},
			[2] = { &c,
				{ &a,
				  NULL, &d,
				  NULL, NULL, &b, NULL },
			},
			[3] = { &d,
				{ &a,
				  NULL, &c,
				  NULL, NULL, &b, NULL },
			},
		},
	},
	[2]  = {
		.pre = TEST4_BACD,
		.sub = {
			[0] = { &a,
				{ &b,
				  NULL, &c,
				  NULL, NULL, NULL, &d },
			},
			[1] = { &b, TEST3_CAD },
			[2] = { &c, TEST3_BAD },
			[3] = { &d, TEST3_BAC },
		},
	},
	[3]  = {
		.pre = TEST4_BACD,
		.sub = {
			[0] = { &a,
				{ &b,
				  NULL, &c,
				  NULL, NULL, NULL, &d },
			},
			[1] = { &b, TEST3_CAD },
			[2] = { &c, TEST3_BAD },
			[3] = { &d, TEST3_BAC },
		},
	},
	[4]  = {
		.pre = TEST4_CADB,
		.sub = {
			[0] = { &a, TEST3_CBD },
			[1] = { &b, TEST3_CAD },
			[2] = { &c,
				{ &d,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
			[3] = { &d,
				{ &c,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
		},
	},
	[5]  = {
		.pre = TEST4_CBDA,
		.sub = {
			[0] = { &a, TEST3_CBD },
			[1] = { &b, TEST3_CAD },
			[2] = { &c,
				{ &d,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
			[3] = { &d,
				{ &c,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
		},
	},

	[6]  = {
		.pre = { &a,
			 NULL, &b,
			 NULL, NULL, NULL, &d,
			 NULL, NULL, NULL, NULL, NULL, NULL, &c, NULL },
		.sub = {
			[0] = { &a,
				{ &b,
				  NULL, &d,
				  NULL, NULL, &c, NULL },
			},
			[1] = { &b,
				{ &a,
				  NULL, &d,
				  NULL, NULL, &c, NULL },
			},
			[2] = { &c,
				{ &a,
				  NULL, &b,
				  NULL, NULL, NULL, &d },
			},
			[3] = { &d,
				{ &a,
				  NULL, &b,
				  NULL, NULL, NULL, &c },
			},
		},
	},
	[7]  = {
		.pre = { &a,
			 NULL, &c,
			 NULL, NULL, &b, &d },
		.sub = {
			[0] = { &a, TEST3_CBD },
			[1] = { &b,
				{ &a,
				  NULL, &c,
				  NULL, NULL, NULL, &d },
			},
			[2] = { &c,
				{ &a,
				  NULL, &d,
				  NULL, NULL, &b, NULL },
			},
			[3] = { &d,
				{ &a,
				  NULL, &c,
				  NULL, NULL, &b, NULL },
			},
		},
	},
	[8]  = {
		.pre = TEST4_BADC,
		.sub = {
			[0] = { &a,
				{ &b,
				  NULL, &d,
				  NULL, NULL, &c, NULL },
			},
			[1] = { &b, TEST3_CAD },
			[2] = { &c, TEST3_BAD },
			[3] = { &d, TEST3_BAC },
		},
	},
	[9]  = {
		.pre = TEST4_BACD,
		.sub = {
			[0] = { &a,
				{ &b,
				  NULL, &c,
				  NULL, NULL, NULL, &d },
			},
			[1] = { &b, TEST3_CAD },
			[2] = { &c, TEST3_BAD },
			[3] = { &d, TEST3_BAC },
		},
	},
	[10] = {
		.pre = TEST4_CADB,
		.sub = {
			[0] = { &a, TEST3_CBD },
			[1] = { &b, TEST3_CAD },
			[2] = { &c,
				{ &d,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
			[3] = { &d,
				{ &c,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
		},
	},
	[11] = {
		.pre = TEST4_CBDA,
		.sub = {
			[0] = { &a, TEST3_CBD },
			[1] = { &b, TEST3_CAD },
			[2] = { &c,
				{ &d,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
			[3] = { &d,
				{ &c,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
		},
	},

	[12] = {
		.pre = { &a,
			 NULL, &d,
			 NULL, NULL, &b, NULL,
			 NULL, NULL, NULL, NULL, NULL, &c, NULL, NULL },
		.sub = {
			[0] = { &a,
				{ &d,
				  &b, NULL,
				  NULL, &c, NULL, NULL },
			},
			[1] = { &b,
				{ &a,
				  NULL, &d,
				  NULL, NULL, &c, NULL },
			},
			[2] = { &c,
				{ &a,
				  NULL, &d,
				  NULL, NULL, &b, NULL },
			},
			[3] = { &d,
				{ &a,
				  NULL, &b,
				  NULL, NULL, NULL, &c },
			},
		},
	},
	[13] = {
		.pre = { &a,
			 NULL, &d,
			 NULL, NULL, &c, NULL,
			 NULL, NULL, NULL, NULL, &b, NULL, NULL, NULL },
		.sub = {
			[0] = { &a,
				{ &d,
				  &c, NULL,
				  &b, NULL, NULL, NULL },
			},
			[1] = { &b,
				{ &a,
				  NULL, &d,
				  NULL, NULL, &c, NULL },
			},
			[2] = { &c,
				{ &a,
				  NULL, &d,
				  NULL, NULL, &b, NULL },
			},
			[3] = { &d,
				{ &a,
				  NULL, &c,
				  NULL, NULL, &b, NULL },
			},
		},
	},
	[14] = {
		.pre = TEST4_BADC,
		.sub = {
			[0] = { &a,
				{ &b,
				  NULL, &d,
				  NULL, NULL, &c, NULL },
			},
			[1] = { &b, TEST3_CAD },
			[2] = { &c, TEST3_BAD },
			[3] = { &d, TEST3_BAC },
		},
	},
	[15] = {
		.pre = TEST4_BADC,
		.sub = {
			[0] = { &a,
				{ &b,
				  NULL, &d,
				  NULL, NULL, &c, NULL },
			},
			[1] = { &b, TEST3_CAD },
			[2] = { &c, TEST3_BAD },
			[3] = { &d, TEST3_BAC },
		},
	},
	[16] = {
		.pre = TEST4_CADB,
		.sub = {
			[0] = { &a, TEST3_CBD },
			[1] = { &b, TEST3_CAD },
			[2] = { &c,
				{ &d,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
			[3] = { &d,
				{ &c,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
		},
	},
	[17] = {
		.pre = TEST4_CBDA,
		.sub = {
			[0] = { &a, TEST3_CBD },
			[1] = { &b, TEST3_CAD },
			[2] = { &c,
				{ &d,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
			[3] = { &d,
				{ &c,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
		},
	},

	[18] = {
		.pre = { &d,
			 &a, NULL,
			 NULL, &b, NULL, NULL,
			 NULL, NULL, NULL, &c, NULL, NULL, NULL, NULL },
		.sub = {
			[0] = { &a,
				{ &d,
				  &b, NULL,
				  NULL, &c, NULL, NULL },
			},
			[1] = { &b,
				{ &d,
				  &a, NULL,
				  NULL, &c, NULL, NULL },
			},
			[2] = { &c,
				{ &d,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
			[3] = { &d,
				{ &a,
				  NULL, &b,
				  NULL, NULL, NULL, &c },
			},
		},
	},
	[19] = {
		.pre = { &d,
			 &a, NULL,
			 NULL, &c, NULL, NULL,
			 NULL, NULL, &b, NULL, NULL, NULL, NULL, NULL },
		.sub = {
			[0] = { &a,
				{ &d,
				  &c, NULL,
				  &b, NULL, NULL, NULL },
			},
			[1] = { &b,
				{ &d,
				  &a, NULL,
				  NULL, &c, NULL, NULL },
			},
			[2] = { &c,
				{ &d,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
			[3] = { &d,
				{ &a,
				  NULL, &c,
				  NULL, NULL, &b, NULL },
			},
		},
	},
	[20] = {
		.pre = { &d,
			 &b, NULL,
			 &a, &c, NULL, NULL},
		.sub = {
			[0] = { &a,
				{ &d,
				  &b, NULL,
				  NULL, &c, NULL, NULL },
			},
			[1] = { &b,
				{ &d,
				  &c, NULL,
				  &a, NULL, NULL, NULL },
			},
			[2] = { &c,
				{ &d,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
			[3] = { &d,
				{ &b,
				  &a, &c },
			},
		},
	},
	[21] = {
		.pre = { &d,
			 &b, NULL,
			 &a, &c, NULL, NULL},
		.sub = {
			[0] = { &a,
				{ &d,
				  &b, NULL,
				  NULL, &c, NULL, NULL },
			},
			[1] = { &b,
				{ &d,
				  &c, NULL,
				  &a, NULL, NULL, NULL },
			},
			[2] = { &c,
				{ &d,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
			[3] = { &d, TEST3_BAC },
		},
	},
	[22] = {
		.pre = { &d,
			 &c, NULL,
			 &a, NULL, NULL, NULL,
			 NULL, &b, NULL, NULL, NULL, NULL, NULL, NULL },
		.sub = {
			[0] = { &a,
				{ &d,
				  &c, NULL,
				  &b, NULL, NULL, NULL },
			},
			[1] = { &b,
				{ &d,
				  &c, NULL,
				  &a, NULL, NULL, NULL },
			},
			[2] = { &c,
				{ &d,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
			[3] = { &d,
				{ &c,
				  &a, NULL,
				  NULL, &b, NULL, NULL },
			},
		},
	},
	[23] = {
		.pre = { &d,
			 &c, NULL,
			 &b, NULL, NULL, NULL,
			 &a, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
		.sub = {
			[0] = { &a,
				{ &d,
				  &c, NULL,
				  &b, NULL, NULL, NULL },
			},
			[1] = { &b,
				{ &d,
				  &c, NULL,
				  &a, NULL, NULL, NULL },
			},
			[2] = { &c,
				{ &d,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
			[3] = { &d,
				{ &c,
				  &b, NULL,
				  &a, NULL, NULL, NULL },
			},
		},
	},
};
